apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: hacbs-test-project-h3cd
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hacbs-test-project-h3cd
    app.kubernetes.io/part-of: rhtap-demo-app
  name: hacbs-test-project-h3cd
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: hacbs-jvm-build-test-project
      app.kubernetes.io/instance: hacbs-test-project-h3cd
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hacbs-jvm-build-test-project
        app.kubernetes.io/instance: hacbs-test-project-h3cd
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-tjds-tenant/rhtap-demo-app/hacbs-test-project-h3cd@sha256:eaf278b8814700084ff0d5a57cab637eb3ad4fb5ecb0d2923031bec8a99d4f08
        name: hacbs-jvm-build-test-project
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
